package com.space.controller;

import com.space.model.Ship;
import com.space.repository.ShipRepo;
import org.springframework.beans.factory.annotation.Autowired;
        import org.springframework.stereotype.Controller;
        import org.springframework.web.bind.annotation.GetMapping;
        import org.springframework.web.bind.annotation.PostMapping;
        import org.springframework.web.bind.annotation.RequestMapping;
        import org.springframework.web.bind.annotation.RequestParam;
        import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/rest") // This means URL's start with /demo (after Application path)
public class ShipController {
  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private ShipRepo shipRepo;

/*  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewUser (@RequestParam String name
          , @RequestParam String email) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    User n = new User();
    n.setName(name);
    n.setEmail(email);
    userRepository.save(n);
    return "Saved";
  }*/

  @GetMapping(path="/ships")
  public @ResponseBody Iterable<Ship> getAllUsers() {
    Iterable<Ship> all = shipRepo.findAll();
    //System.out.println("aaaa = " + all.iterator().next().toString());
    return all;
  }
}